export enum QueryKeys {
  getAnswers = "getAnswers",
  getSnippets = "getSnippets",
  getSnippet = "getSnippet",
  markSnippet = "markSnippet",
  addComment = "addComment",
  createSnippet = "createSnippet",
  login = "login",
  logout = "logout",
  register = "register",
  getMe = "getMe",
  getUserStats = "getUserStats",
  getUsers = "getUsers",
  getUser = "getUser",
  changeMyUsername = "changeMyUsername",
  deleteMe = "deleteMe",
  changePassword = "changePassword",
  getFAQs = "getFAQs",
  getFAQ = "getFAQ",
  createFAQ = "createFAQ",
  updateFAQ = "updateFAQ",
}
